### ISSUE TITLE
Suggestions for lazy package manager

### ISSUE THREAD

**Issue by boydkelly** [theHamsta/nvim_rocks#3]
Hi,

A  lot have moved to lazy package manager, but it doesn't support luarocks as Packer does.  
Are there any configuration suggestions that will provide some functionality?

Hopefully the 'use packer for maintained version' will be reverted!!!!  

Thanks for nvim_rocks!

**Comment by theHamsta** [comment]
Hi! I haven't used this package for ages and don't know whether it still works. Does it work for you with lazy?

**Comment by boydkelly** [comment]
Well below basically worked for me.   But once it seems to be installed its there.   I don't know the ensure_installed is really necessary.   And maybe you just have to install what you need and then disable the plugin to save a few ms.

````
return {
  {
    "theHamsta/nvim_rocks",
    -- event = "VeryLazy",
    build = "pip3 install --user hererocks && python3 -mhererocks . -j2.1.0-beta3 -r3.0.0 && cp nvim_rocks.lua lua",
    config = function()
      local nvim_rocks = require "nvim_rocks"
      nvim_rocks.ensure_installed "uuid"
    end,
  },
}
````

**Comment by theHamsta** [comment]
> Well below basically worked for me. But once it seems to be installed its there. I don't know the ensure_installed is really necessary. And maybe you just have to install what you need and then disable the plugin to save a few ms.
> 
> ```
> return {
>   {
>     "theHamsta/nvim_rocks",
>     -- event = "VeryLazy",
>     build = "pip3 install --user hererocks && python3 -mhererocks . -j2.1.0-beta3 -r3.0.0 && cp nvim_rocks.lua lua",
>     config = function()
>       local nvim_rocks = require "nvim_rocks"
>       nvim_rocks.ensure_installed "uuid"
>     end,
>   },
> }
> ```

Happy to hear that it works for you. The `ensure_installed` should just do a quick check every time whether the installed module is still there. You can use lazy's profile times to see if it causes any noticable delay. `ensure_installed` is thought to automatically set up fresh installs or installs were the cache folder got deleted. You can also just manually install your favorite packages or force the install when a require to your favorite package fails.

I can add your snippet to the readme for lazy users
